version: '3.6'
services:
  php:
    build: './myphp'
    volumes:
      - ./www:/var/www/html
    ports:
      - 8080:80
    links:
      - "mysql"
  myadmin:
    image: phpmyadmin:latest
    environment:
      PMA_HOST: mysql
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: root
      PMA_PMADB: mariadb
    ports:
      - 8081:80
    links:
      - "mysql"
    
  mysql:
    image: mariadb:latest
    environment:
      MARIADB_USER: user
      MARIADB_PASSWORD: user
      MARIADB_ROOT_PASSWORD: root
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306